# serverless.yml
service: muffin-serverless

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: '/'
      - http:
          method: ANY
          path: '/{proxy+}'
plugins:
  - serverless-offline
  - serverless-plugin-typescript